# Generated by Django 4.1.5 on 2023-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='duration of the quix in minutes'),
        ),
    ]
